apiVersion: v1
kind: Pod
metadata:
  name: lca-agent-once
spec:
  restartPolicy: Never
  containers:
    - name: lca-agent
      image: lca_node:v2
      imagePullPolicy: IfNotPresent # may lead to caching issues, but efficient for development
      env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
      command: ["/bin/bash", "-c"] 
      args:
        - |
          /app/host_info.sh postgres 5432 "$DB_NAME" "$DB_USER" "$DB_PASSWORD"
          /app/host_usage.sh postgres 5432 "$DB_NAME" "$DB_USER" "$DB_PASSWORD"